### ISSUE TITLE
Question regarding the fieldset element.

### ISSUE THREAD

**Issue by ilkaypolat1985** [BTAkademi-Frontend-31Temmuz/HW-3#5]

**Comment by ilkaypolat1985** [comment]
Hocam selamlar,

Odev dokumaninda belirtilen bir gereksinim su sekilde: "Fieldset element must be in the form"

Form icine fieldset elementini koymamizin faydasi tam olarak ne olacak? 

@ICetinkaya

**Comment by ICetinkaya** [comment]
Selam İlkay,

Mesela Personel kişisel bilgilerini kullanmak icin fieldset yazdın sadece o
alanla ilgili bilgileri giricek. Biraz daha hangi alanı nereye yazman
gerektiği ile ilgili yardimci olmak icin kullanılıyor . Yazdığın alanları
bir grup haline getirmek icin kullanılıyor. Ornegin personel iicin yazdığın
fieldsette zipcode olmamalıdır. Personel ile ilgili bilgileri girmelidir

İyi akşamlar

11 Ağu 2021 Çar 23:44 tarihinde ilkay Polat ***@***.***> şunu
yazdı:

**Comment by ilkaypolat1985** [comment]
Anladim hocam tesekkurler.
